services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - rabbitmq.env

  stock-publisher:
    build:
      context: ./stock-publisher
      dockerfile: Dockerfile
    container_name: stock-publisher
    restart: always
    environment:
      RABBITMQ_URL: amqp://stockmarket:12345678@localhost:5672/

    depends_on:
      - rabbitmq